name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      # - name: 🦑 Personal metrics
        # - uses: lowlighter/metrics@latest
        #   with:
        #     filename: metrics.plugin.calendar.svg
        #     token: ${{ secrets.METRICS_TOKEN }}
        #     committer_token: ${{ secrets.GITHUB_TOKEN }}
        #     base: ""
        #     plugin_lines: yes
        #     plugin_isocalendar: yes
        #     plugin_isocalendar_duration: full-year
        #     plugin_stars: yes
        #     plugin_stars_limit: 2
        #     plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
             # - name: 🦑 Personal metrics (anilist)
        # if: ${{ success() || failure() }}
        - uses: lowlighter/metrics@master
          with:
            filename: metrics.plugin.personal.anilist.svg
            token: NOT_NEEDED
            committer_token: ${{ secrets.GITHUB_TOKEN }}
            plugin_anilist: yes
            plugin_anilist_medias: anime, manga
            plugin_anilist_sections: favorites, characters
            plugin_anilist_limit: 2
            plugin_anilist_shuffle: yes
            plugin_anilist_limit_characters: 22
            plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
            
