# See https://github.com/lowlighter/metrics for documentation
# This worflow is scheduled for every hour, and also run after each commit (GitHub action excluded) on master/main branch
# - name: Metrics embed
# uses: lowlighter/metrics@v3.34
            
# name: Metrics
# on:
#   schedule:
#     - cron: "0 0-22/2 * * *"
#   push:
#     branches:
#       - main
#   workflow_dispatch:
# jobs:
#   github-metrics-personal:
#     runs-on: ubuntu-latest
#     steps:
          
#       - name: 🦑 Personal metrics (anilist)
#         if: ${{ success() || failure() }}
#         uses: lowlighter/metrics@v3.34
#         with:
#           filename: metrics.plugin.personal.anilist.svg
#           token: NOT_NEEDED
#           committer_token: ${{ secrets.GITHUB_TOKEN }}
#           plugin_anilist: yes
#           plugin_anilist_medias: anime, manga
#           plugin_anilist_sections: favorites, characters
#           plugin_anilist_limit: 2
#           plugin_anilist_shuffle: yes
#           plugin_anilist_limit_characters: 22
#           plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}


# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.testREADME }}

          # Options
          user: errantProgrammer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites
          plugin_anilist_shuffle: yes
          plugin_anilist_user: errantProgrammer
